<?php

    function ThisFooter(){

        $Fotter =   '<section class="info_section layout_padding2-top">'
        
                        .'<div class="container">'
                        
                        .'<div class="container">'
                        .'<div class="row">'
                            .'<div class="col-md-3">'
                            .'<h6>'
                                .'Sobre Power Fitness'
                            .'</h6>'
                            .'<p>'
                                .'Somos a maior academia da região Sul do Brasil com 4 academias em operação, uma estrutura de 3 andares, e
                                '
                                .'proporcionando equipamentos de ponta para sua melhor experiência'
                            .'</p>'
                            .'</div>'
                            .'<div class="col-md-2 offset-md-1">'
                            .'<h6>'
                                .'Menu'
                            .'</h6>'
                            .'<ul>'
                                .'<li class=" active">'
                                .'<a class="" href="index.html">Pagina Oficial <span class="sr-only">(current)</span></a>'
                                .'</li>'
                            .'</ul>'
                            .'</div>'
                            .'<div class="col-md-3">'
                            .'<h6>'
                                .'Link de acesso'
                            .'</h6>'
                            .'<ul>'
                                .'<li>'
                                .'<a href="">'
                                    .'Modalidades'
                                .'</a>'
                                .'</li>'
                                
                            .'</ul>'
                            .'</div>'
                            .'<div class="col-md-3">'
                            .'<h6>'
                                .'Entre em Contato'
                            .'</h6>'
                            .'<div class="info_link-box">'
                                .'<a href="">'
                                .'<img src="images/location-white.png" alt="">'
                                .'<span> Centro de Joinvlle</span>'
                                .'</a>'
                                .'<a href="">'
                                .'<img src="images/call-white.png" alt="">'
                                .'<span>+554799544144</span>'
                                .'</a>'
                                .'<a href="">'
                                .'<img src="images/mail-white.png" alt="">'
                                .'<span> Bombfit@gmail.com</span>'
                                .'</a>'
                            .'</div>'
                            .'<div class="info_social">'
                                .'<div>'
                                .'<a href="">'
                                    .'<img src="images/facebook-logo-button.png" alt="">'
                                .'</a>'
                                .'</div>'
                                .'<div>'
                                .'<a href="">'
                                    .'<img src="images/twitter-logo-button.png" alt="">'
                                .'</a>'
                                .'</div>'
                                .'<div>'
                                .'<a href="">'
                                    .'<img src="images/linkedin.png" alt="">'
                                .'</a>'
                                .'</div>'
                                .'<div>'
                                .'<a href="">'
                                    .'<img src="images/instagram.png" alt="">'
                                .'</a>'
                                .'</div>'
                            .'</div>'
                            .'</div>'
                        .'</div>'
                        .'</div>'
                    .'</section>'
                        
                    .'<section class="container-fluid footer_section ">'
                    .'<hr>'
                        .'<p>'
                        
                            .'&copy; 2021 Todos Direitos Reservados. Design by '
                            .'<a href="https://html.design/">Clervens And Carol</a>'
                        .'</p>'
                    .'</section>';
        
        return $Fotter;    

    }

?>